const seedProjects=[
 {id:'sdds',name:'SDDS Project',company:'Latiteam Co., Ltd.',client:'สำนักงานพัฒนารัฐบาลดิจิทัล',desc:'ระบบบริหารและเชื่อมโยงชุดข้อมูลภาครัฐ',progress:76,status:'active',deadline:'2026-07-15',value:1850000,cost:720000,wht:3,paid:'ชำระแล้ว 60%',color:'#315bea',manager:'ณัฐวุฒิ',team:['กท','นว','ศพ'],tasks:[['ออกแบบ UX/UI Dashboard',100,'ศิริพร'],['พัฒนา API เชื่อมต่อข้อมูล',72,'ณัฐวุฒิ'],['ทดสอบระบบและ UAT',45,'กานต์']]},
 {id:'sdc',name:'SDC Project',company:'Latiteam Co., Ltd.',client:'บริษัท สยามดาต้า จำกัด',desc:'แพลตฟอร์มรวบรวมและวิเคราะห์ข้อมูลลูกค้า',progress:58,status:'risk',deadline:'2026-06-28',value:980000,cost:510000,wht:3,paid:'รอชำระงวด 2',color:'#ff9f43',manager:'พิมพ์ชนก',team:['พช','กท','อน'],tasks:[['Data Mapping',90,'พิมพ์ชนก'],['Dashboard Analytics',55,'กานต์'],['Data Migration',30,'อนุชา']]},
 {id:'jmt',name:'JMT Project',company:'Data Cube Co., Ltd.',client:'บริษัท เจ เอ็ม ที เน็ทเวอร์ค เซอร์วิสเซ็ส จำกัด',desc:'ระบบติดตาม KPI และรายงานผลการดำเนินงาน',progress:88,status:'active',deadline:'2026-07-05',value:2400000,cost:940000,wht:3,paid:'ชำระแล้ว 80%',color:'#19a8b8',manager:'อนุชา',team:['อน','นว','พช'],tasks:[['KPI Configuration',100,'อนุชา'],['Executive Report',92,'ณัฐวุฒิ'],['Training',70,'พิมพ์ชนก']]},
 {id:'crm',name:'CRM Revamp',company:'Latiteam Co., Ltd.',client:'บริษัท ไบรท์ รีเทล จำกัด',desc:'ปรับปรุงระบบ CRM และ Customer Journey',progress:100,status:'done',deadline:'2026-06-10',value:650000,cost:280000,wht:3,paid:'ชำระครบแล้ว',color:'#38c58b',manager:'ศิริพร',team:['ศพ','กท'],tasks:[['Research',100,'ศิริพร'],['Implementation',100,'กานต์'],['Handover',100,'ศิริพร']]}
];
const seedUpdates=[
 {date:'2026-06-19T09:40:00',project:'sdds',task:'พัฒนา API เชื่อมต่อข้อมูล',from:65,to:72,note:'เชื่อมต่อ API ชุดข้อมูลหลักสำเร็จ 4 จาก 6 รายการ',user:'ณัฐวุฒิ วงศ์ดี'},
 {date:'2026-06-18T16:15:00',project:'jmt',task:'Executive Report',from:85,to:92,note:'เพิ่มตัวกรองรายไตรมาสและตรวจสอบสูตร KPI แล้ว',user:'อนุชา กิตติ'},
 {date:'2026-06-18T11:20:00',project:'sdc',task:'Dashboard Analytics',from:48,to:55,note:'ปรับกราฟตามข้อเสนอแนะลูกค้า รอข้อมูลชุดสุดท้าย',user:'กานต์ เทพดี'},
 {date:'2026-06-17T14:05:00',project:'sdds',task:'ทดสอบระบบและ UAT',from:30,to:45,note:'ทดสอบ Scenario หลักผ่าน 18 จาก 24 รายการ',user:'ศิริพร ใจดี'},
 {date:'2026-06-14T10:00:00',project:'crm',task:'Handover',from:90,to:100,note:'ส่งมอบคู่มือและปิดโครงการเรียบร้อย',user:'ศิริพร ใจดี'}
];
let projects=JSON.parse(localStorage.getItem('latiteam-projects')||'null')||seedProjects;
let updates=JSON.parse(localStorage.getItem('latiteam-updates')||'null')||seedUpdates;
let currentRole='executive',selectedProject='all',statusFilter='all';
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const statusText={active:'กำลังดำเนินการ',risk:'ต้องเฝ้าระวัง',done:'เสร็จแล้ว'};
const roleConfig={executive:{title:'ภาพรวมองค์กร',projects:['all']},manager:{title:'พื้นที่ผู้จัดการโครงการ',projects:['all']},team:{title:'งานที่ได้รับมอบหมาย',projects:['sdds','jmt']},accounting:{title:'บัญชีและการเงิน',projects:['all']}};
const money=n=>new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB',maximumFractionDigits:0}).format(n);
const validDate=d=>{const value=new Date(d);return d&&!Number.isNaN(value.getTime())?value:null};
const dateTH=d=>{const value=validDate(d);return value?new Intl.DateTimeFormat('th-TH',{day:'numeric',month:'short',year:'2-digit'}).format(value):'ยังไม่กำหนด'};
const timeTH=d=>{const value=validDate(d);return value?value.toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'})+' น.':'ไม่ระบุเวลา'};
const visibleProjects=()=>{let p=projects;if(currentRole==='team')p=p.filter(x=>roleConfig.team.projects.includes(x.id));if(selectedProject!=='all')p=p.filter(x=>x.id===selectedProject);return p};
const canViewMoney=()=>currentRole!=='team'&&!document.body.classList.contains('finance-denied');
function save(){localStorage.setItem('latiteam-projects',JSON.stringify(projects));localStorage.setItem('latiteam-updates',JSON.stringify(updates))}
function showToast(msg){const t=$('#toast');t.textContent='✓  '+msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function projectOptions(){const allowed=currentRole==='team'?projects.filter(p=>roleConfig.team.projects.includes(p.id)):projects;$('#projectFilter').innerHTML='<option value="all">ทุกโปรเจกต์</option>'+allowed.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');$('#updateProject').innerHTML=allowed.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');selectedProject='all'}
function renderStats(){const p=visibleProjects(),value=p.reduce((a,x)=>a+(Number(x.value)||0),0),avg=Math.round(p.reduce((a,x)=>a+x.progress,0)/(p.length||1)),followUps=p.reduce((sum,x)=>sum+(x.workstreams||[]).filter(w=>w.followUp).length,0);const cards=[['โปรเจกต์ทั้งหมด',p.length,'project','#315bea','โครงการที่เข้าถึงได้'],['กำลังดำเนินการ',p.filter(x=>x.status!=='done').length,'clock','#19a8b8',`${p.filter(x=>x.status==='risk').length} โครงการต้องเฝ้าระวัง`],['ความคืบหน้าเฉลี่ย',avg+'%','trend','#38c58b','คำนวณจากงานที่ได้รับสิทธิ์'],canViewMoney()?['มูลค่าโครงการ',money(value),'money','#ff9f43','ตามสิทธิ์ที่ได้รับ']:['รายการติดตาม',followUps,'follow','#ff9f43','ไม่รวมข้อมูลการเงิน']];$('#statsGrid').innerHTML=cards.map(x=>`<div class="stat-card" style="--accent:${x[3]}"><div class="stat-top"><span>${x[0]}</span><span class="stat-icon stat-icon-${x[2]}" aria-hidden="true"></span></div><div class="stat-value">${x[1]}</div><div class="stat-note">${x[4]}</div></div>`).join('')}
function renderPortfolio(){const p=visibleProjects();$('#portfolioList').innerHTML=p.map(x=>`<div class="portfolio-row" data-project="${x.id}"><div class="project-name"><span class="project-logo" style="background:${x.color}">${x.name.slice(0,2).toUpperCase()}</span><div><b>${x.name}</b><small>${x.company}</small></div></div><div class="progress-wrap"><div class="progress-copy"><span>Progress</span><b>${x.progress}%</b></div><div class="mini-progress"><span style="width:${x.progress}%;background:${x.color}"></span></div></div><span class="status-badge ${x.status}">${statusText[x.status]}</span><div class="card-avatars">${x.team.slice(0,3).map(a=>`<span>${a}</span>`).join('')}</div></div>`).join('');$$('[data-project]').forEach(e=>e.onclick=()=>showDetail(e.dataset.project));const active=p.filter(x=>x.status==='active').length,risk=p.filter(x=>x.status==='risk').length,done=p.filter(x=>x.status==='done').length,avg=Math.round(p.reduce((a,x)=>a+x.progress,0)/(p.length||1));$('#overallChart').innerHTML=`<div class="chart-body"><div class="donut" style="--p:${avg}"><div class="donut-copy"><b>${avg}%</b><small>เฉลี่ยทั้งหมด</small></div></div><div class="legend"><div><i style="background:#315bea"></i>กำลังดำเนินการ <b>${active}</b></div><div><i style="background:#ff9f43"></i>เฝ้าระวัง <b>${risk}</b></div><div><i style="background:#38c58b"></i>เสร็จแล้ว <b>${done}</b></div></div></div>`}
function renderActivities(){const allowed=visibleProjects().map(p=>p.id),list=updates.filter(u=>allowed.includes(u.project)).slice(0,4);$('#activityList').innerHTML=list.map(u=>{const p=projects.find(x=>x.id===u.project);return`<div class="activity-item"><span class="activity-avatar">${(u.user||'-').slice(0,2)}</span><div class="activity-copy"><b>${u.user||'-'} อัปเดต ${p?.name||'-'}</b><p>${u.task} จาก ${u.from}% เป็น ${u.to}%</p></div><span class="activity-time">${dateTH(u.date)}</span></div>`}).join('');const deadlines=visibleProjects().filter(x=>x.status!=='done'&&validDate(x.deadline)).sort((a,b)=>validDate(a.deadline)-validDate(b.deadline)).slice(0,3);$('#deadlineList').innerHTML=deadlines.map(p=>{const d=validDate(p.deadline);return`<div class="deadline-item"><div class="deadline-date">${d.getDate()}<small>${new Intl.DateTimeFormat('th-TH',{month:'short'}).format(d)}</small></div><div class="deadline-copy"><b>${p.name}</b><p>${p.client}</p></div><small>${p.status==='risk'?'เร่งด่วน':'ตามแผน'}</small></div>`}).join('')||'<div class="empty-state">ยังไม่มีโปรเจคที่ระบุวันสิ้นสุด</div>'}
function renderProjects(){const q=($('#projectSearch')?.value||'').toLowerCase();let p=visibleProjects().filter(x=>(statusFilter==='all'||x.status===statusFilter)&&(x.name+x.client+x.company).toLowerCase().includes(q));$('#projectGrid').innerHTML=p.map(x=>`<article class="project-card" data-project="${x.id}"><div class="card-top"><span class="project-logo" style="background:${x.color}">${x.name.slice(0,2).toUpperCase()}</span><span class="status-badge ${x.status}">${statusText[x.status]}</span></div><h3>${x.name}</h3><p>${x.desc}</p><div class="progress-copy"><span>ความคืบหน้า</span><b>${x.progress}%</b></div><div class="mini-progress"><span style="width:${x.progress}%;background:${x.color}"></span></div><div class="card-meta"><span>กำหนดส่ง ${dateTH(x.deadline)}</span><div class="card-avatars">${x.team.map(a=>`<span>${a}</span>`).join('')}</div></div></article>`).join('')||'<div class="panel">ไม่พบโปรเจกต์ที่ค้นหา</div>';$$('[data-project]').forEach(e=>e.onclick=()=>showDetail(e.dataset.project))}
function showDetail(id){const p=projects.find(x=>x.id===id);if(!p)return;const moneyKpi=canViewMoney()?`<div><small>มูลค่าโครงการ</small><b>${money(p.value)}</b></div>`:`<div><small>ผู้รับผิดชอบ</small><b>${p.manager||'ยังไม่กำหนด'}</b></div>`,financeDetails=canViewMoney()?`<div class="permission-row"><b>ภาษีหัก ณ ที่จ่าย</b><span>${p.wht||0}%</span></div><div class="permission-row"><b>สถานะชำระเงิน</b><span>${p.paid||'ยังไม่ระบุ'}</span></div>`:'';$('#projectDetail').innerHTML=`<div class="detail-hero"><div class="detail-nav"><button class="back-button" data-goto="projects">← กลับไปโปรเจกต์</button><span class="status-badge ${p.status}">${statusText[p.status]}</span></div><div class="detail-title"><span class="project-logo" style="background:${p.color}">${p.name.slice(0,2).toUpperCase()}</span><div><h2>${p.name}</h2><p>${p.client} · ดูแลโดย ${p.manager}</p></div></div><div class="detail-kpis"><div><small>ความคืบหน้า</small><b>${p.progress}%</b></div><div><small>กำหนดส่ง</small><b>${dateTH(p.deadline)}</b></div>${moneyKpi}<div><small>KPI งานย่อย</small><b>${p.tasks.filter(t=>t[1]===100).length}/${p.tasks.length} สำเร็จ</b></div></div></div><div class="detail-grid"><div class="panel"><div class="panel-head"><div><span class="eyebrow">WORK BREAKDOWN</span><h3>Progress งานย่อย</h3></div><button class="primary" data-open-update data-project-id="${p.id}">+ อัปเดต</button></div>${p.tasks.map(t=>`<div class="task-row"><div><b>${t[0]}</b><small>ผู้รับผิดชอบ: ${t[2]}</small></div><div class="mini-progress"><span style="width:${t[1]}%;background:${p.color}"></span></div><b>${t[1]}%</b></div>`).join('')}</div><div><div class="panel"><span class="eyebrow">PROJECT DETAILS</span><h3>ข้อมูลโครงการ</h3><div class="permission-row"><b>บริษัทผู้รับจ้าง</b><span>${p.company}</span></div><div class="permission-row"><b>บริษัทลูกค้า</b><span>${p.client}</span></div>${financeDetails}</div></div></div>`;showView('detail');bindDynamic();$$('[data-open-update]').forEach(b=>b.onclick=()=>openUpdate(b.dataset.projectId))}
function renderUpdates(){const allowed=visibleProjects().map(p=>p.id);$('#updateTable').innerHTML=updates.filter(u=>allowed.includes(u.project)).map(u=>{const p=projects.find(x=>x.id===u.project);return`<tr><td>${dateTH(u.date)}<br><small>${timeTH(u.date)}</small></td><td><b>${p?.name||'-'}</b><br><small>${u.task}</small></td><td><span class="delta">${u.from}% → ${u.to}%</span></td><td>${u.note}</td><td>${u.user}</td></tr>`}).join('')}
function renderFinance(){if(!canViewMoney()){if($('#financeStats'))$('#financeStats').innerHTML='';if($('#financeTable'))$('#financeTable').innerHTML='';return}const p=visibleProjects(),value=p.reduce((a,x)=>a+(Number(x.value)||0),0),cost=p.reduce((a,x)=>a+(Number(x.cost)||0),0),profit=value-cost,wht=p.reduce((a,x)=>a+(Number(x.value)||0)*(Number(x.wht)||0)/100,0);$('#financeStats').innerHTML=[['มูลค่าโครงการรวม',money(value),'money','#315bea'],['ค่าใช้จ่ายรวม',money(cost),'cost','#ef5b5b'],['กำไรคาดการณ์',money(profit),'trend','#38c58b'],['ภาษีหัก ณ ที่จ่าย',money(wht),'tax','#ff9f43']].map(x=>`<div class="stat-card" style="--accent:${x[3]}"><div class="stat-top"><span>${x[0]}</span><span class="stat-icon stat-icon-${x[2]}" aria-hidden="true"></span></div><div class="stat-value">${x[1]}</div></div>`).join('');$('#financeTable').innerHTML=p.map(x=>`<tr><td class="finance-name"><b>${x.client}</b><small>${x.name} · ${x.company}</small></td><td>${money(x.value||0)}</td><td>${money(x.cost||0)}</td><td><span class="delta">${money((x.value||0)-(x.cost||0))}</span></td><td>${x.wht||0}% (${money((x.value||0)*(x.wht||0)/100)})</td><td><span class="status-badge ${(x.paid||'').includes('ครบ')?'done':'active'}">${x.paid||'ยังไม่ระบุ'}</span></td></tr>`).join('')}
function renderUsers(){const users=[['กานต์ เทพดี','ผู้บริหาร','ทุกโปรเจกต์'],['ณัฐวุฒิ วงศ์ดี','ผู้จัดการโครงการ','SDDS, JMT'],['พิมพ์ชนก แสงใส','ผู้จัดการโครงการ','SDC'],['ศิริพร ใจดี','ทีมงาน','SDDS, CRM'],['อนุชา กิตติ','ทีมงาน','SDC, JMT'],['วริศรา มั่นคง','ฝ่ายบัญชี','ทุกโปรเจกต์']];$('#userList').innerHTML=users.map((u,i)=>`<div class="user-row"><div class="user-info"><span class="avatar">${u[0].slice(0,2)}</span><div><b>${u[0]}</b><small>ใช้งานล่าสุด วันนี้</small></div></div><select><option>${u[1]}</option></select><span class="project-tags">${u[2]}</span></div>`).join('')}
function renderAll(){renderStats();renderPortfolio();renderActivities();renderProjects();renderUpdates();renderFinance();renderUsers()}
const titles={dashboard:'ภาพรวมองค์กร',projects:'โปรเจกต์ทั้งหมด',detail:'รายละเอียดโปรเจกต์',updates:'ประวัติการอัปเดต',finance:'บัญชีและการเงิน',access:'สิทธิ์การเข้าถึง'};
function showView(name){if(name==='finance'&&!canViewMoney()){name='dashboard';showToast('บัญชีนี้ไม่มีสิทธิ์ดูข้อมูลการเงิน')}$$('.view').forEach(v=>v.classList.remove('active'));$(`#${name}View`)?.classList.add('active');$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===name));$('#pageTitle').textContent=titles[name]||'';document.querySelector('.sidebar').classList.remove('open');scrollTo({top:0,behavior:'smooth'})}
function bindDynamic(){$$('[data-goto]').forEach(b=>b.onclick=()=>showView(b.dataset.goto))}
function openUpdate(id){$('#updateProject').value=id||visibleProjects()[0]?.id;$('#updateModal').classList.add('open');$('#updateModal').setAttribute('aria-hidden','false')}
function closeUpdate(){$('#updateModal').classList.remove('open');$('#updateModal').setAttribute('aria-hidden','true')}
function exportCSV(finance=false){let rows;if(finance){rows=[['บริษัทลูกค้า','โปรเจกต์','มูลค่า','ค่าใช้จ่าย','กำไร','หัก ณ ที่จ่าย','สถานะชำระ'],...visibleProjects().map(p=>[p.client,p.name,p.value,p.cost,p.value-p.cost,p.wht+'%',p.paid])]}else{const range=$('#exportRange').value,now=new Date('2026-06-19T23:59:59'),days=range==='daily'?1:range==='weekly'?7:9999;rows=[['วันเวลา','โปรเจกต์','งาน','ก่อนหน้า','ปัจจุบัน','รายละเอียด','แก้ไขโดย'],...updates.filter(u=>(now-new Date(u.date))/864e5<=days).map(u=>[new Date(u.date).toLocaleString('th-TH'),projects.find(p=>p.id===u.project)?.name,u.task,u.from,u.to,u.note,u.user])]}const csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=finance?'latiteam-finance.csv':'latiteam-updates.csv';a.click();URL.revokeObjectURL(a.href);showToast('Export ไฟล์เรียบร้อยแล้ว')}
$$('.nav-item').forEach(n=>n.onclick=()=>{if(currentRole==='accounting'&&!['finance','dashboard'].includes(n.dataset.view))return showToast('สิทธิ์ฝ่ายบัญชีเข้าถึงเมนูนี้ไม่ได้');showView(n.dataset.view)});bindDynamic();
$('#roleSelect').onchange=e=>{currentRole=e.target.value;$('.admin-only').classList.toggle('hidden',!['executive','manager'].includes(currentRole));$('.manager-only')?.classList.toggle('hidden',!['executive','manager'].includes(currentRole));projectOptions();renderAll();if(currentRole==='accounting')showView('finance');else showView('dashboard');$('#pageTitle').textContent=roleConfig[currentRole].title;showToast('เปลี่ยนมุมมองสิทธิ์แล้ว')};
$('#projectFilter').onchange=e=>{selectedProject=e.target.value;renderAll()};$('#projectSearch').oninput=renderProjects;$$('.filter-pills button').forEach(b=>b.onclick=()=>{$$('.filter-pills button').forEach(x=>x.classList.remove('active'));b.classList.add('active');statusFilter=b.dataset.status;renderProjects()});
$$('[data-open-update]').forEach(b=>b.onclick=()=>openUpdate());$$('.close-modal').forEach(b=>b.onclick=closeUpdate);$('#updateModal').onclick=e=>{if(e.target===$('#updateModal'))closeUpdate()};
$('#updateForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter,id=$('#updateProject').value,p=projects.find(x=>x.id===id),to=Number($('#updateProgress').value),task=$('#updateTask').value.trim(),existing=p.tasks.find(t=>t[0]===task),from=existing?existing[1]:p.progress,file=$('#updateFile')?.files[0];button.disabled=true;try{const attachment=file&&window.LatiteamSupabase?await window.LatiteamSupabase.uploadFile(file,id):{};if(existing)existing[1]=to;else p.tasks.push([task,to,'กานต์']);p.progress=Math.round(p.tasks.reduce((a,t)=>a+t[1],0)/p.tasks.length);p.status=$('#updateStatus').value;updates.unshift({date:new Date().toISOString(),project:id,task,from,to,note:$('#updateNote').value.trim(),user:'กานต์ เทพดี',link:$('#updateLink')?.value.trim()||attachment.signedUrl||'',fileName:attachment.fileName||'',storagePath:attachment.storagePath||''});save();renderAll();closeUpdate();e.target.reset();showToast('บันทึกความคืบหน้าและเอกสารแล้ว')}catch(error){showToast(error.message)}finally{button.disabled=false}};
$('#exportButton').onclick=()=>exportCSV(false);$('#exportFinance').onclick=()=>exportCSV(true);$('#menuButton').onclick=()=>$('.sidebar').classList.toggle('open');$('#notificationButton').onclick=()=>showToast('มี 2 โปรเจกต์ใกล้ถึงกำหนดส่ง');$('#addProjectButton').onclick=()=>showToast('ฟังก์ชันเพิ่มโปรเจกต์พร้อมเชื่อมต่อฐานข้อมูลในระบบจริง');
projectOptions();renderAll();
