(() => {
  const config = window.LATITEAM_SUPABASE_CONFIG || {};
  const financeKeys = ['value','monthlyRevenue','billingType','cost','costStatus','wht','whtStatus','paid'];
  let db = null;
  let authSession = null;
  let sessionUser = null;
  let cloudUsers = [];
  let memberships = [];
  let saveTimer = null;
  let syncing = false;
  let editingUserId = '';
  let realtimeChannel = null;
  let realtimeTimer = null;

  function installUi() {
    document.body.classList.add('auth-locked');
    document.body.insertAdjacentHTML('beforeend', `
      <section class="login-screen" id="loginScreen"><div class="login-card">
        <div class="login-brand"><span>L</span><div><b>Latiteam</b><small>PROJECT TRACKING · SUPABASE</small></div></div>
        <div><span class="eyebrow">SECURE ACCESS</span><h1>เข้าสู่ระบบ</h1><p>กรอกบัญชีที่ Admin สร้างให้ ระบบจะแสดงเฉพาะโปรเจคและข้อมูลที่ได้รับสิทธิ์</p></div>
        <form id="loginForm"><label>ชื่อผู้ใช้<input id="loginUsername" autocomplete="username" required></label><label>รหัสผ่าน<input id="loginPassword" type="password" autocomplete="current-password" minlength="8" required></label><div class="login-error" id="loginError"></div><button class="primary login-submit" type="submit">เข้าสู่ระบบ</button></form>
        <small class="login-security">บัญชีผู้ใช้และ Session จัดการโดย Supabase Auth</small>
      </div></section>
      <button id="cloudSyncBadge" class="cloud-user-badge" type="button" hidden><span id="cloudAvatar" class="cloud-avatar"></span><span id="cloudUserLabel"></span></button><button id="cloudLogoutButton" class="cloud-logout-button" type="button" hidden>ออกจากระบบ</button><div id="systemClock" class="system-clock" hidden></div>
      <div id="systemLoading" class="system-loading" hidden><div class="loading-card"><span class="loading-spinner"></span><b id="loadingTitle">กำลังดำเนินการ</b><small id="loadingDetail"></small></div></div><div id="notificationStack" class="notification-stack" aria-live="polite"></div>
      <div class="modal-backdrop" id="createUserModal"><div class="modal wide-modal"><div class="modal-head"><div><span class="eyebrow">ADMIN USER MANAGEMENT</span><h2>สร้างผู้ใช้งาน</h2></div><button type="button" class="close-create-user">×</button></div><form id="createUserForm"><div class="form-row"><label>ชื่อผู้ใช้<input id="newUsername" required pattern="[a-z0-9._-]{3,40}"></label><label>ชื่อที่แสดง<input id="newDisplayName" required></label></div><div class="form-row"><label>รหัสผ่านชั่วคราว<input id="newPassword" type="password" minlength="8" required></label><label>Role<select id="newRole"><option value="team">ทีมงาน</option><option value="manager">ผู้จัดการโครงการ</option><option value="executive">ผู้บริหาร</option><option value="accounting">ฝ่ายบัญชี</option><option value="admin">ผู้ดูแลระบบ</option></select></label></div><div class="user-project-pickers"><fieldset><legend>โปรเจคที่มองเห็น</legend><div id="newAllowedProjects"></div></fieldset><fieldset id="financeProjectFieldset"><legend>โปรเจคที่เห็นข้อมูลเงิน</legend><div id="newFinanceProjects"></div></fieldset></div><p id="teamFinanceNotice" class="permission-notice hidden">ทีมงานจะไม่เห็นเมนู มูลค่า ค่าใช้จ่าย กำไร หรือภาษีทุกกรณี</p><label class="checkbox-line"><input id="newCanEdit" type="checkbox"> อนุญาตให้แก้ไขและอัปเดตงาน</label><div class="login-error" id="createUserError"></div><div class="modal-actions"><button type="button" class="secondary close-create-user">ยกเลิก</button><button class="primary" type="submit">บันทึกผู้ใช้</button></div></form></div></div>
      <div class="modal-backdrop" id="profileModal"><div class="modal profile-modal"><div class="modal-head"><div><span class="eyebrow">MY PROFILE</span><h2>โปรไฟล์ของฉัน</h2></div><button type="button" class="close-profile">×</button></div><form id="profileForm"><div class="profile-preview" id="profilePreview"></div><label>ชื่อที่แสดง<input id="profileDisplayName" required></label><fieldset class="avatar-choice"><legend>รูปโปรไฟล์</legend><label><input type="radio" name="avatarMode" value="initials" checked> แสดงอักษรย่อจากชื่อ</label><label><input type="radio" name="avatarMode" value="image"> ใช้รูปภาพของฉัน</label></fieldset><label id="avatarFileField" class="hidden">เลือกรูป JPG, PNG หรือ WebP ไม่เกิน 5 MB<input id="profileAvatarFile" type="file" accept="image/jpeg,image/png,image/webp"></label><div class="login-error" id="profileError"></div><div class="modal-actions"><button type="button" class="secondary close-profile">ยกเลิก</button><button class="primary" type="submit">บันทึกโปรไฟล์</button></div></form></div></div>`);
    document.querySelector('#loginForm').onsubmit = login;
    document.querySelector('#cloudLogoutButton').onclick = logout;
    document.querySelector('#cloudSyncBadge').onclick = openProfile;
    document.querySelectorAll('.close-create-user').forEach(button => button.onclick = () => document.querySelector('#createUserModal').classList.remove('open'));
    document.querySelector('#createUserForm').onsubmit = saveUser;
    document.querySelector('#newRole').onchange = updateFinancePickerState;
    document.querySelectorAll('.close-profile').forEach(button => button.onclick = () => document.querySelector('#profileModal').classList.remove('open'));
    document.querySelector('#profileForm').onsubmit = saveProfile;
    document.querySelectorAll('input[name="avatarMode"]').forEach(input => input.onchange = updateProfilePreview);
    document.querySelector('#profileAvatarFile').onchange = updateProfilePreview;
    document.querySelector('#profileDisplayName').oninput = updateProfilePreview;
    const headerAvatar=document.querySelector('.user-control .avatar');if(headerAvatar){headerAvatar.onclick=openProfile;headerAvatar.title='แก้ไขรูปโปรไฟล์';headerAvatar.setAttribute('role','button');headerAvatar.tabIndex=0;headerAvatar.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')openProfile()}}
    updateClock();setInterval(updateClock,1000);
  }

  function ensureConfigured() {
    if (!config.url || !config.anonKey || /PASTE_/.test(config.url + config.anonKey)) throw new Error('ยังไม่ได้ตั้งค่า Supabase URL และ anon key ใน supabase-config.js');
    if (!window.supabase?.createClient) throw new Error('โหลด Supabase SDK ไม่สำเร็จ');
    if (!db) db = window.supabase.createClient(config.url, config.anonKey, { auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: true } });
    return db;
  }
  function timestamp(){return new Intl.DateTimeFormat('th-TH',{dateStyle:'medium',timeStyle:'medium',hour12:false}).format(new Date())}
  function updateClock(){const node=document.querySelector('#systemClock');if(node)node.innerHTML=`<b>${new Intl.DateTimeFormat('th-TH',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date())} น.</b><small>${new Intl.DateTimeFormat('th-TH',{weekday:'short',day:'numeric',month:'short',year:'numeric'}).format(new Date())}</small>`}
  function showLoading(title,detail='กรุณารอสักครู่'){const node=document.querySelector('#systemLoading');if(!node)return;document.querySelector('#loadingTitle').textContent=title;document.querySelector('#loadingDetail').textContent=`${detail} · ${timestamp()}`;node.hidden=false}
  function hideLoading(){const node=document.querySelector('#systemLoading');if(node)node.hidden=true}
  function notify(message,type='success'){const root=document.querySelector('#notificationStack');if(!root)return;const item=document.createElement('div');item.className=`system-notification ${type}`;item.innerHTML=`<b>${type==='error'?'ไม่สำเร็จ':type==='info'?'แจ้งเตือน':'ดำเนินการสำเร็จ'}</b><span>${message}</span><small>${timestamp()}</small><button type="button">×</button>`;item.querySelector('button').onclick=()=>item.remove();root.prepend(item);setTimeout(()=>item.remove(),6000)}
  function showLogin(message=''){document.body.classList.add('auth-locked');document.querySelector('#loginScreen').hidden=false;document.querySelector('#loginError').textContent=message;document.querySelector('#cloudSyncBadge').hidden=true;document.querySelector('#cloudLogoutButton').hidden=true;document.querySelector('#systemClock').hidden=true}
  function safeDate(value,withTime=false){if(value==null||value==='')return'';if(typeof value==='number'||/^\d{5}(?:\.\d+)?$/.test(String(value))){const date=new Date(Date.UTC(1899,11,30)+Number(value)*86400000);return withTime?date.toISOString():date.toISOString().slice(0,10)}const date=new Date(value);if(Number.isNaN(date.getTime()))return'';return withTime?date.toISOString():date.toISOString().slice(0,10)}
  function normalizeProject(project){project.startDate=safeDate(project.startDate);project.deadline=safeDate(project.deadline);(project.workstreams||[]).forEach(stream=>{stream.start=safeDate(stream.start);stream.due=safeDate(stream.due);stream.followUp=safeDate(stream.followUp);(stream.items||[]).forEach(item=>{item.start=safeDate(item.start);item.due=safeDate(item.due);item.followUp=safeDate(item.followUp)})});(project.meetings||[]).forEach(item=>item.date=safeDate(item.date));return project}
  function assertResult(result){if(result.error)throw result.error;return result.data||[]}

  async function login(event){event.preventDefault();const button=event.submitter,errorNode=document.querySelector('#loginError');errorNode.textContent='';button.disabled=true;showLoading('กำลังเข้าสู่ระบบ','Supabase กำลังตรวจสอบบัญชีและสิทธิ์');try{ensureConfigured();const username=document.querySelector('#loginUsername').value.trim().toLowerCase();const email=`${username}@${config.usernameDomain||'latiteam.local'}`;const {data,error}=await db.auth.signInWithPassword({email,password:document.querySelector('#loginPassword').value});if(error)throw error;authSession=data.session;await enterApp();notify(`ยินดีต้อนรับ ${sessionUser.name}`)}catch(error){errorNode.textContent=error.message;notify(error.message,'error')}finally{hideLoading();button.disabled=false}}
  async function enterApp(){ensureConfigured();const {data:{session}}=await db.auth.getSession();if(!session)throw new Error('Session หมดอายุ กรุณาเข้าสู่ระบบใหม่');authSession=session;await loadIdentity();if(!sessionUser.active)throw new Error('บัญชีนี้ถูกปิดใช้งาน');if(sessionUser.mustChangePassword)await forcePasswordChange();document.body.classList.remove('auth-locked');document.querySelector('#loginScreen').hidden=true;document.querySelector('#cloudSyncBadge').hidden=false;document.querySelector('#cloudLogoutButton').hidden=false;document.querySelector('#systemClock').hidden=false;currentRole=sessionUser.role;renderSessionUser();applyFinanceVisibility();const roleSelect=document.querySelector('#roleSelect');if(roleSelect){roleSelect.value=currentRole;roleSelect.disabled=true}document.querySelectorAll('.admin-only').forEach(element=>element.classList.toggle('hidden',currentRole!=='admin'));document.querySelectorAll('.manager-only').forEach(element=>element.classList.toggle('hidden',!['admin','manager'].includes(currentRole)));await pull();startRealtime()}
  async function loadIdentity(){const userId=authSession.user.id;const [profileResult,memberResult]=await Promise.all([db.from('profiles').select('*').eq('id',userId).single(),db.from('project_members').select('*').eq('user_id',userId)]);if(profileResult.error)throw profileResult.error;memberships=memberResult.data||[];sessionUser=mapUser(profileResult.data,memberships)}
  async function forcePasswordChange(){const password=prompt('เข้าสู่ระบบครั้งแรก กรุณาตั้งรหัสผ่านใหม่อย่างน้อย 8 ตัวอักษร');if(!password||password.length<8)throw new Error('ต้องตั้งรหัสผ่านใหม่อย่างน้อย 8 ตัวอักษร');const result=await db.auth.updateUser({password});if(result.error)throw result.error;const rpc=await db.rpc('complete_password_change');if(rpc.error)throw rpc.error;sessionUser.mustChangePassword=false;notify('เปลี่ยนรหัสผ่านเรียบร้อยแล้ว')}
  async function logout(){showLoading('กำลังออกจากระบบ');try{if(realtimeChannel){await db.removeChannel(realtimeChannel);realtimeChannel=null}if(db)await db.auth.signOut()}finally{authSession=null;sessionUser=null;hideLoading();showLogin();notify('ออกจากระบบเรียบร้อยแล้ว')}}

  async function pull(){syncing=true;try{const queries=[db.from('projects').select('*').order('name'),db.from('project_finance').select('*'),db.from('project_updates').select('*').order('occurred_at',{ascending:false}),db.from('events').select('*').order('event_date'),db.from('project_members').select('*')];if(sessionUser.role==='admin')queries.push(db.from('profiles').select('*').order('display_name'));const results=await Promise.all(queries);results.forEach(result=>{if(result.error)throw result.error});const [projectRows,financeRows,updateRows,eventRows,memberRows,profileRows={data:[]}]=results;memberships=memberRows.data||[];const financeMap=Object.fromEntries((financeRows.data||[]).map(row=>[row.project_id,row.data||{}]));projects=(projectRows.data||[]).map(row=>{const project=normalizeProject({...row.data,id:row.id,name:row.name,...(financeMap[row.id]||{})});Object.defineProperty(project,'_createdBy',{value:row.created_by,enumerable:false,writable:true});return project});updates=(updateRows.data||[]).map(row=>({...row.data,date:safeDate(row.occurred_at,true),project:row.project_id,_id:row.id}));if(typeof standaloneEvents!=='undefined'){standaloneEvents=(eventRows.data||[]).map(row=>({...row.data,id:row.id,projectId:row.project_id||'',date:safeDate(row.event_date)}));await Promise.all(standaloneEvents.map(async event=>{if(!event.storagePath)return;const signed=await db.storage.from('project-files').createSignedUrl(event.storagePath,3600);if(!signed.error)event.link=signed.data.signedUrl}))}cloudUsers=(profileRows.data||[]).map(profile=>mapUser(profile,memberships.filter(member=>member.user_id===profile.id)));roleConfig.team.projects=projects.map(project=>project.id);localStorage.setItem('latiteam-projects',JSON.stringify(projects));localStorage.setItem('latiteam-updates',JSON.stringify(updates));projectOptions();renderAll()}finally{syncing=false}}
  function splitProject(project){const data=structuredClone(project),finance={};financeKeys.forEach(key=>{finance[key]=data[key]??null;delete data[key]});return{data,finance}}
  async function push(){if(!sessionUser?.canEdit&&sessionUser?.role!=='admin')return;syncing=true;try{const financeRows=[];for(const project of projects){const split=splitProject(project);const projectRow={name:project.name,data:split.data};const existing=Boolean(project._createdBy);if(existing){assertResult(await db.from('projects').update(projectRow).eq('id',project.id))}else{assertResult(await db.from('projects').insert({...projectRow,id:project.id,created_by:authSession.user.id}));project._createdBy=authSession.user.id}if(sessionUser.role!=='team'&&(sessionUser.role==='admin'||sessionUser.financeProjects.includes(project.id)))financeRows.push({project_id:project.id,data:split.finance})}if(financeRows.length)assertResult(await db.from('project_finance').upsert(financeRows));const updateRows=updates.filter(item=>item.project).map(item=>{item._id=item._id||crypto.randomUUID();return{id:item._id,project_id:item.project,occurred_at:safeDate(item.date,true)||new Date().toISOString(),data:Object.fromEntries(Object.entries(item).filter(([key])=>key!=='_id'))}});if(updateRows.length)assertResult(await db.from('project_updates').upsert(updateRows));const eventRows=(typeof standaloneEvents==='undefined'?[]:standaloneEvents).map(item=>({id:item.id||crypto.randomUUID(),project_id:item.projectId||null,event_date:safeDate(item.date)||null,data:Object.fromEntries(Object.entries(item).filter(([key])=>key!=='fileData'))}));if(eventRows.length)assertResult(await db.from('events').upsert(eventRows));notify('บันทึกข้อมูลลง Supabase แล้ว')}catch(error){notify(error.message,'error');throw error}finally{syncing=false}}
  function schedulePush(){if(!config.autoSave||syncing||!authSession||(!sessionUser?.canEdit&&sessionUser?.role!=='admin'))return;clearTimeout(saveTimer);saveTimer=setTimeout(()=>push().catch(()=>{}),700)}
  function startRealtime(){if(realtimeChannel)return;const refresh=()=>{clearTimeout(realtimeTimer);realtimeTimer=setTimeout(async()=>{if(syncing)return;try{await pull();notify('ข้อมูลถูกอัปเดตจากทีมแบบ Realtime','info')}catch(error){notify(error.message,'error')}},500)};realtimeChannel=db.channel('latiteam-live').on('postgres_changes',{event:'*',schema:'public',table:'projects'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'project_finance'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'project_updates'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'events'},refresh).subscribe()}

  function mapUser(profile,userMemberships=[]){return{id:profile.id,username:profile.username,name:profile.display_name,role:profile.role,active:profile.active,mustChangePassword:profile.must_change_password,avatarMode:profile.avatar_mode||'initials',avatarPath:profile.avatar_path||'',allowedProjects:userMemberships.map(item=>item.project_id),financeProjects:profile.role==='team'?[]:userMemberships.filter(item=>item.can_finance).map(item=>item.project_id),canEdit:profile.role==='admin'||userMemberships.some(item=>item.can_edit),canCreateProjects:profile.can_create_projects}}
  function initials(name=''){return name.trim().split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join('').toUpperCase()||'U'}
  async function avatarUrl(path){if(!path)return'';const result=await db.storage.from('profile-avatars').createSignedUrl(path,3600);return result.error?'':result.data.signedUrl}
  async function renderSessionUser(){const avatar=document.querySelector('#cloudAvatar'),headerAvatar=document.querySelector('.user-control .avatar'),label=document.querySelector('#cloudUserLabel');if(!avatar||!label||!sessionUser)return;label.textContent=`${sessionUser.name} · ${roleName(sessionUser.role)}`;[avatar,headerAvatar].filter(Boolean).forEach(node=>{node.textContent=initials(sessionUser.name);node.style.backgroundImage='';node.classList.remove('has-photo')});if(sessionUser.avatarMode==='image'&&sessionUser.avatarPath){const url=await avatarUrl(sessionUser.avatarPath);if(url)[avatar,headerAvatar].filter(Boolean).forEach(node=>{node.textContent='';node.style.backgroundImage=`url("${url}")`;node.classList.add('has-photo')})}}
  function applyFinanceVisibility(){const allowed=sessionUser&&sessionUser.role!=='team'&&(sessionUser.role==='admin'||sessionUser.role==='accounting'||sessionUser.financeProjects.length>0);document.body.classList.toggle('finance-denied',!allowed);document.querySelectorAll('[data-view="finance"],#financeView').forEach(node=>node.classList.toggle('hidden',!allowed));if(!allowed&&document.querySelector('#financeView')?.classList.contains('active'))showView('dashboard')}
  function updateFinancePickerState(){const isTeam=document.querySelector('#newRole')?.value==='team',field=document.querySelector('#financeProjectFieldset'),notice=document.querySelector('#teamFinanceNotice');field?.classList.toggle('hidden',isTeam);notice?.classList.toggle('hidden',!isTeam);if(isTeam)field?.querySelectorAll('input').forEach(input=>input.checked=false)}
  async function openProfile(){if(!sessionUser)return;document.querySelector('#profileDisplayName').value=sessionUser.name;document.querySelector(`input[name="avatarMode"][value="${sessionUser.avatarMode||'initials'}"]`).checked=true;document.querySelector('#profileAvatarFile').value='';document.querySelector('#profileError').textContent='';await updateProfilePreview();document.querySelector('#profileModal').classList.add('open')}
  async function updateProfilePreview(){const mode=document.querySelector('input[name="avatarMode"]:checked')?.value||'initials',file=document.querySelector('#profileAvatarFile').files[0],preview=document.querySelector('#profilePreview'),name=document.querySelector('#profileDisplayName').value||sessionUser?.name||'';document.querySelector('#avatarFileField').classList.toggle('hidden',mode!=='image');preview.textContent=initials(name);preview.style.backgroundImage='';if(mode==='image'){let url='';if(file)url=URL.createObjectURL(file);else if(sessionUser?.avatarPath)url=await avatarUrl(sessionUser.avatarPath);if(url){preview.textContent='';preview.style.backgroundImage=`url("${url}")`}}}
  async function saveProfile(event){event.preventDefault();const mode=document.querySelector('input[name="avatarMode"]:checked').value,file=document.querySelector('#profileAvatarFile').files[0],name=document.querySelector('#profileDisplayName').value.trim(),errorNode=document.querySelector('#profileError');errorNode.textContent='';try{showLoading('กำลังบันทึกโปรไฟล์');let path=sessionUser.avatarPath||'';if(mode==='image'&&file){if(file.size>5242880)throw new Error('รูปภาพต้องมีขนาดไม่เกิน 5 MB');path=`${authSession.user.id}/avatar-${Date.now()}.${file.name.split('.').pop().toLowerCase()}`;const upload=await db.storage.from('profile-avatars').upload(path,file,{upsert:false,contentType:file.type});if(upload.error)throw upload.error}if(mode==='image'&&!path)throw new Error('กรุณาเลือกรูปภาพ');const result=await db.rpc('update_my_profile',{new_display_name:name,new_avatar_mode:mode,new_avatar_path:mode==='image'?path:null});if(result.error)throw result.error;sessionUser.name=name;sessionUser.avatarMode=mode;sessionUser.avatarPath=mode==='image'?path:'';await renderSessionUser();document.querySelector('#profileModal').classList.remove('open');notify('บันทึกโปรไฟล์แล้ว')}catch(error){errorNode.textContent=error.message;notify(error.message,'error')}finally{hideLoading()}}
  function renderCloudUsers(){const root=document.querySelector('#userList');if(!root)return;if(sessionUser?.role!=='admin'){root.innerHTML='<div class="empty-state">เฉพาะ Admin เท่านั้นที่จัดการผู้ใช้ได้</div>';return}root.innerHTML=`<div class="user-management-head"><p>บัญชีจริงจาก Supabase Auth และสิทธิ์ RLS</p><button class="primary" id="openCreateUser">+ เพิ่มผู้ใช้</button></div>${cloudUsers.map(user=>`<div class="user-row cloud-user-row"><div class="user-info"><span class="avatar">${user.name.slice(0,2)}</span><div><b>${user.name}</b><small>@${user.username} · ${roleName(user.role)}</small></div></div><span class="project-tags">${user.role==='admin'?'ทุกโปรเจค':user.allowedProjects.join(', ')||'ยังไม่กำหนด'}</span><span class="status-badge ${user.active?'done':'risk'}">${user.active?'ใช้งาน':'ปิด'}</span><div class="user-actions"><button class="secondary edit-cloud-user" data-id="${user.id}">แก้ไข</button>${user.id!==sessionUser.id?`<button class="danger delete-cloud-user" data-id="${user.id}">ลบ</button>`:''}</div></div>`).join('')}`;document.querySelector('#openCreateUser').onclick=()=>openUserEditor();document.querySelectorAll('.edit-cloud-user').forEach(button=>button.onclick=()=>openUserEditor(button.dataset.id));document.querySelectorAll('.delete-cloud-user').forEach(button=>button.onclick=()=>deleteUser(button.dataset.id))}
  function renderChecks(id,selected=[]){document.querySelector(id).innerHTML=projects.map(project=>`<label><input type="checkbox" value="${project.id}" ${selected.includes(project.id)?'checked':''}> ${project.name}</label>`).join('')}
  function openUserEditor(userId=''){editingUserId=userId;const user=cloudUsers.find(item=>item.id===userId),form=document.querySelector('#createUserForm');form.reset();document.querySelector('#createUserModal h2').textContent=user?'แก้ไขผู้ใช้งาน':'สร้างผู้ใช้งาน';document.querySelector('#newUsername').disabled=Boolean(user);document.querySelector('#newUsername').value=user?.username||'';document.querySelector('#newDisplayName').value=user?.name||'';document.querySelector('#newRole').value=user?.role||'team';const password=document.querySelector('#newPassword');password.required=!user;password.closest('label').style.display=user?'none':'';document.querySelector('#newCanEdit').checked=Boolean(user?.canEdit);renderChecks('#newAllowedProjects',user?.allowedProjects||[]);renderChecks('#newFinanceProjects',user?.financeProjects||[]);updateFinancePickerState();document.querySelector('#createUserModal').classList.add('open')}
  async function adminRequest(action,user={}){const response=await fetch(`${config.url}/functions/v1/admin-users`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${authSession.access_token}`,'apikey':config.anonKey},body:JSON.stringify({action,user,userId:user.id})});const result=await response.json();if(!response.ok||result.error)throw new Error(result.error||'จัดการผู้ใช้ไม่สำเร็จ');return result}
  async function saveUser(event){event.preventDefault();const checked=id=>[...document.querySelectorAll(`#${id} input:checked`)].map(input=>input.value),existing=cloudUsers.find(item=>item.id===editingUserId),role=document.querySelector('#newRole').value;const user={id:editingUserId,username:document.querySelector('#newUsername').value.trim(),name:document.querySelector('#newDisplayName').value.trim(),password:document.querySelector('#newPassword').value,role,allowed_projects:checked('newAllowedProjects'),finance_projects:role==='team'?[]:checked('newFinanceProjects'),can_edit:document.querySelector('#newCanEdit').checked,active:existing?.active!==false,mustChangePassword:existing?.mustChangePassword};try{showLoading('กำลังบันทึกผู้ใช้');const result=await adminRequest(editingUserId?'update':'create',user);const index=cloudUsers.findIndex(item=>item.id===result.user.id);if(index>=0)cloudUsers[index]=result.user;else cloudUsers.push(result.user);document.querySelector('#createUserModal').classList.remove('open');editingUserId='';renderCloudUsers();notify(index>=0?'แก้ไขผู้ใช้แล้ว':'สร้างผู้ใช้แล้ว')}catch(error){document.querySelector('#createUserError').textContent=error.message;notify(error.message,'error')}finally{hideLoading()}}
  async function deleteUser(userId){const user=cloudUsers.find(item=>item.id===userId);if(!user||!confirm(`ลบบัญชี ${user.name} ใช่หรือไม่`))return;showLoading('กำลังลบผู้ใช้');try{await adminRequest('delete',{id:userId});cloudUsers=cloudUsers.filter(item=>item.id!==userId);renderCloudUsers();notify('ลบผู้ใช้แล้ว')}catch(error){notify(error.message,'error')}finally{hideLoading()}}
  async function uploadFile(file,projectId='general'){ensureConfigured();const safeName=`${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`,path=`${projectId||'general'}/${safeName}`;const result=await db.storage.from('project-files').upload(path,file,{upsert:false});if(result.error)throw result.error;const signed=await db.storage.from('project-files').createSignedUrl(path,3600);if(signed.error)throw signed.error;return{storagePath:path,fileName:file.name,signedUrl:signed.data.signedUrl}}
  async function saveFinance(project){if(!sessionUser||sessionUser.role==='team'||!(sessionUser.role==='admin'||sessionUser.role==='accounting'||sessionUser.financeProjects.includes(project.id)))throw new Error('บัญชีนี้ไม่มีสิทธิ์แก้ไขข้อมูลการเงิน');const split=splitProject(project),result=await db.from('project_finance').upsert({project_id:project.id,data:split.finance});if(result.error)throw result.error;notify('บันทึกข้อมูลการเงินแล้ว')}
  function roleName(role){return({admin:'ผู้ดูแลระบบ',executive:'ผู้บริหาร',manager:'ผู้จัดการโครงการ',team:'ทีมงาน',accounting:'ฝ่ายบัญชี'})[role]||role}

  const originalRenderUsers=renderUsers;
  renderUsers=()=>sessionUser?renderCloudUsers():originalRenderUsers();
  window.addEventListener('load',async()=>{installUi();window.showToast=message=>notify(message);showToast=window.showToast;const localSave=save;save=function(){localSave();schedulePush()};try{ensureConfigured();const {data:{session}}=await db.auth.getSession();if(session){showLoading('กำลังเปิดระบบ','กำลังโหลดข้อมูลล่าสุด');authSession=session;await enterApp();notify('เชื่อมต่อ Supabase แล้ว')}else showLogin()}catch(error){showLogin(error.message);notify(error.message,'error')}finally{hideLoading()}});
  window.LatiteamSupabase={pull,push,logout,uploadFile,saveFinance};window.LatiteamCloud=window.LatiteamSupabase;
})();
